#include <world/generators/MAIN_TEST_SUITE_WORLD_GENERATORS.h>

INCLUDE_SUB_SUITES(WORLD_GENERATORS, 3,
INCLUDE_SUITE(generator_test_world),
INCLUDE_SUITE(generator_flat_world),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(WORLD_GENERATORS, END_TESTS);

