#include <collisions/MAIN_TEST_SUITE_COLLISIONS.h>

INCLUDE_SUB_SUITES(COLLISIONS, 3,
INCLUDE_SUITE(collision_manager),
INCLUDE_SUITE(hitbox_aabb),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(COLLISIONS, END_TESTS);

