#include <entity/handlers/animation/MAIN_TEST_SUITE_ENTITY_HANDLERS_ANIMATION.h>

INCLUDE_SUB_SUITES(ENTITY_HANDLERS_ANIMATION, 2,
INCLUDE_SUITE(animation_handler__humanoid),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_HANDLERS_ANIMATION, END_TESTS);

