#include <world/structures/implemented/MAIN_TEST_SUITE_WORLD_STRUCTURES_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(WORLD_STRUCTURES_IMPLEMENTED, 1,NULL);

DEFINE_SUITE_WITH__SUB_SUITES(WORLD_STRUCTURES_IMPLEMENTED, END_TESTS);

