#include <entity/handlers/MAIN_TEST_SUITE_ENTITY_HANDLERS.h>

INCLUDE_SUB_SUITES(ENTITY_HANDLERS, 6,
INCLUDE_SUITE(entity_handlers),
INCLUDE_SUITE(ENTITY_HANDLERS_BODY),
INCLUDE_SUITE(ENTITY_HANDLERS_AI),
INCLUDE_SUITE(ENTITY_HANDLERS_ANIMATION),
INCLUDE_SUITE(ENTITY_HANDLERS_COLLISION),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_HANDLERS, END_TESTS);

