#include <sort/sort_list/MAIN_TEST_SUITE_SORT_SORT_LIST.h>

INCLUDE_SUB_SUITES(SORT_SORT_LIST, 5,
INCLUDE_SUITE(sort_list),
INCLUDE_SUITE(sort_node),
INCLUDE_SUITE(sort_list_manager),
INCLUDE_SUITE(heap_sort),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SORT_SORT_LIST, END_TESTS);

