#include <rendering/MAIN_TEST_SUITE_RENDERING.h>

INCLUDE_SUB_SUITES(RENDERING, 6,
INCLUDE_SUITE(animate_humanoid),
INCLUDE_SUITE(animate_sprite),
INCLUDE_SUITE(sprite),
INCLUDE_SUITE(animate_entity),
INCLUDE_SUITE(RENDERING_FONT),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(RENDERING, END_TESTS);

