#include <entity/implemented/player/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_PLAYER.h>

INCLUDE_SUB_SUITES(ENTITY_IMPLEMENTED_PLAYER, 3,
INCLUDE_SUITE(entity__player),
INCLUDE_SUITE(ENTITY_IMPLEMENTED_PLAYER_AI),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_IMPLEMENTED_PLAYER, END_TESTS);

