#include <entity/implemented/bird/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_BIRD.h>

INCLUDE_SUB_SUITES(ENTITY_IMPLEMENTED_BIRD, 1,NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_IMPLEMENTED_BIRD, END_TESTS);

