#include "zombie/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_ZOMBIE.h"
#include "fox/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_FOX.h"
#include "skeleton/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_SKELETON.h"
#include "bird/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_BIRD.h"
#include "player/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_PLAYER.h"
#include "cow/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_COW.h"
#include "rabbit/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_RABBIT.h"
#include "frog/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_FROG.h"

#include <test_util.h>

DECLARE_SUITE(ENTITY_IMPLEMENTED);

