
$(OFILES_CORE):
	mkdir -p $(BUILD)/$$(dirname $@)
	$(CC) $(LIBS) $(INCLUDE) $(FLAGS) -o $(BUILD)/$@ -c $(SOURCE_CORE)/$(@:.o=.c) 

ifneq ($(BUILD), $(BUILD_NDS))

#---------------------------------------------------------------------------------
$(SPRITE_FILES) :
	@mkdir -p $(BUILD)/$(dir $@)
	$(SILENTCMD)cp $(BASE_DIR)/core/$@ $(BUILD)/$@
#---------------------------------------------------------------------------------

endif
