#include <entity/implemented/player/ai/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_PLAYER_AI.h>

INCLUDE_SUB_SUITES(ENTITY_IMPLEMENTED_PLAYER_AI, 2,
INCLUDE_SUITE(ai_handler__player),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_IMPLEMENTED_PLAYER_AI, END_TESTS);

