#include <entity/implemented/frog/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_FROG.h>

INCLUDE_SUB_SUITES(ENTITY_IMPLEMENTED_FROG, 1,NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_IMPLEMENTED_FROG, END_TESTS);

