#include "world/tiles/tile__cover__walls.h"
#include "defines_weak.h"
#include "world/tile_logic_manager.h"

void register_tile_handlers_for__walls(
        Tile_Logic_Manager *p_tile_logic_managers) {
    register_tile_logic_record_for__cover_kind(
            p_tile_logic_managers, 
            Tile_Cover_Kind__Wall__Stone, 
            TILE_LOGIC_RECORD(
                0, 
                0, 
                0, 
                0, 
                TILE_LOGIC_FLAGS__NONE, 
                Tool_Kind__Pickaxe, 
                Item_Kind__Pile__Stone__Plenty, 
                1));
    register_tile_logic_record_for__cover_kind(
            p_tile_logic_managers, 
            Tile_Cover_Kind__Wall__Amethyst, 
            TILE_LOGIC_RECORD(
                0, 
                0, 
                0, 
                0, 
                TILE_LOGIC_FLAGS__NONE, 
                Tool_Kind__Pickaxe, 
                Item_Kind__Pile__Amethyst__Plenty, 
                1));
    register_tile_logic_record_for__cover_kind(
            p_tile_logic_managers, 
            Tile_Cover_Kind__Wall__Diamond, 
            TILE_LOGIC_RECORD(
                0, 
                0, 
                0, 
                0, 
                TILE_LOGIC_FLAGS__NONE, 
                Tool_Kind__Pickaxe, 
                Item_Kind__Pile__Diamond__Plenty, 
                1));
    register_tile_logic_record_for__cover_kind(
            p_tile_logic_managers, 
            Tile_Cover_Kind__Wall__Gold, 
            TILE_LOGIC_RECORD(
                0, 
                0, 
                0, 
                0, 
                TILE_LOGIC_FLAGS__NONE, 
                Tool_Kind__Pickaxe, 
                Item_Kind__Pile__Gold__Plenty, 
                1));
    register_tile_logic_record_for__cover_kind(
            p_tile_logic_managers, 
            Tile_Cover_Kind__Wall__Iron, 
            TILE_LOGIC_RECORD(
                0, 
                0, 
                0, 
                0, 
                TILE_LOGIC_FLAGS__NONE, 
                Tool_Kind__Pickaxe, 
                Item_Kind__Pile__Iron__Plenty, 
                1));
    register_tile_logic_record_for__cover_kind(
            p_tile_logic_managers, 
            Tile_Cover_Kind__Wall__Stone, 
            TILE_LOGIC_RECORD(
                0, 
                0, 
                0, 
                0, 
                TILE_LOGIC_FLAGS__NONE, 
                Tool_Kind__Pickaxe, 
                Item_Kind__Pile__Stone__Plenty, 
                1));
    register_tile_logic_record_for__cover_kind(
            p_tile_logic_managers, 
            Tile_Cover_Kind__Wall__Stone_Brick, 
            TILE_LOGIC_RECORD(
                0, 
                0, 
                0, 
                0, 
                TILE_LOGIC_FLAGS__NONE, 
                Tool_Kind__Pickaxe, 
                Item_Kind__Pile__Stone_Brick__Plenty, 
                1));
    register_tile_logic_record_for__cover_kind(
            p_tile_logic_managers, 
            Tile_Cover_Kind__Wall__Sandstone, 
            TILE_LOGIC_RECORD(
                0, 
                0, 
                0, 
                0, 
                TILE_LOGIC_FLAGS__NONE, 
                Tool_Kind__Pickaxe, 
                Item_Kind__Pile__Sandstone__Plenty, 
                1));
    register_tile_logic_record_for__cover_kind(
            p_tile_logic_managers, 
            Tile_Cover_Kind__Wall__Dirt, 
            TILE_LOGIC_RECORD(
                0, 
                0, 
                0, 
                0, 
                TILE_LOGIC_FLAGS__NONE, 
                Tool_Kind__Shovel, 
                Item_Kind__Pile__Dirt__Plenty, 
                1));
    register_tile_logic_record_for__cover_kind(
            p_tile_logic_managers, 
            Tile_Cover_Kind__Wall__Sand, 
            TILE_LOGIC_RECORD(
                0, 
                0, 
                0, 
                0, 
                TILE_LOGIC_FLAGS__NONE, 
                Tool_Kind__Shovel, 
                Item_Kind__Pile__Sand__Plenty, 
                1));
    register_tile_logic_record_for__cover_kind(
            p_tile_logic_managers, 
            Tile_Cover_Kind__Wall__Oak_Wood, 
            TILE_LOGIC_RECORD(
                0, 
                0, 
                0, 
                0, 
                TILE_LOGIC_FLAGS__NONE, 
                Tool_Kind__Hatchet, 
                Item_Kind__Pile__Wood__Plenty, 
                1));
}
