#include <world/path_finding/process/MAIN_TEST_SUITE_WORLD_PATH_FINDING_PROCESS.h>

INCLUDE_SUB_SUITES(WORLD_PATH_FINDING_PROCESS, 2,
INCLUDE_SUITE(process_path_finding),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(WORLD_PATH_FINDING_PROCESS, END_TESTS);

