#include <inventory/MAIN_TEST_SUITE_INVENTORY.h>

INCLUDE_SUB_SUITES(INVENTORY, 4,
INCLUDE_SUITE(item_stack),
INCLUDE_SUITE(inventory),
INCLUDE_SUITE(item),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(INVENTORY, END_TESTS);

