#include <entity/handlers/ai/MAIN_TEST_SUITE_ENTITY_HANDLERS_AI.h>

INCLUDE_SUB_SUITES(ENTITY_HANDLERS_AI, 2,
INCLUDE_SUITE(ai_handler__dummy),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_HANDLERS_AI, END_TESTS);

