#include <entity/handlers/collision/MAIN_TEST_SUITE_ENTITY_HANDLERS_COLLISION.h>

INCLUDE_SUB_SUITES(ENTITY_HANDLERS_COLLISION, 2,
INCLUDE_SUITE(collision_handler__default),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_HANDLERS_COLLISION, END_TESTS);

