#include <entity/MAIN_TEST_SUITE_ENTITY.h>

INCLUDE_SUB_SUITES(ENTITY, 4,
INCLUDE_SUITE(entity_manager),
INCLUDE_SUITE(entity),
INCLUDE_SUITE(CONTROLLERS),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY, END_TESTS);

