#include <entity/MAIN_TEST_SUITE_ENTITY.h>

INCLUDE_SUB_SUITES(ENTITY, 7,
INCLUDE_SUITE(reserves),
INCLUDE_SUITE(entity_manager),
INCLUDE_SUITE(entity),
INCLUDE_SUITE(humanoid),
INCLUDE_SUITE(ENTITY_IMPLEMENTED),
INCLUDE_SUITE(ENTITY_HANDLERS),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY, END_TESTS);

