#include <game_action/MAIN_TEST_SUITE_GAME_ACTION.h>

INCLUDE_SUB_SUITES(GAME_ACTION, 3,
INCLUDE_SUITE(game_action),
INCLUDE_SUITE(game_actions__singleplayer),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(GAME_ACTION, END_TESTS);

