#include <entity/implemented/zombie/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_ZOMBIE.h>

INCLUDE_SUB_SUITES(ENTITY_IMPLEMENTED_ZOMBIE, 3,
INCLUDE_SUITE(entity__zombie),
INCLUDE_SUITE(ENTITY_IMPLEMENTED_ZOMBIE_AI),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_IMPLEMENTED_ZOMBIE, END_TESTS);

