#include <entity/implemented/rabbit/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_RABBIT.h>

INCLUDE_SUB_SUITES(ENTITY_IMPLEMENTED_RABBIT, 1,NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_IMPLEMENTED_RABBIT, END_TESTS);

