#include <entity/implemented/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED.h>

INCLUDE_SUB_SUITES(ENTITY_IMPLEMENTED, 9,
INCLUDE_SUITE(ENTITY_IMPLEMENTED_ZOMBIE),
INCLUDE_SUITE(ENTITY_IMPLEMENTED_FOX),
INCLUDE_SUITE(ENTITY_IMPLEMENTED_SKELETON),
INCLUDE_SUITE(ENTITY_IMPLEMENTED_BIRD),
INCLUDE_SUITE(ENTITY_IMPLEMENTED_PLAYER),
INCLUDE_SUITE(ENTITY_IMPLEMENTED_COW),
INCLUDE_SUITE(ENTITY_IMPLEMENTED_RABBIT),
INCLUDE_SUITE(ENTITY_IMPLEMENTED_FROG),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_IMPLEMENTED, END_TESTS);

