#include <world/structures/MAIN_TEST_SUITE_WORLD_STRUCTURES.h>

INCLUDE_SUB_SUITES(WORLD_STRUCTURES, 5,
INCLUDE_SUITE(room),
INCLUDE_SUITE(structure),
INCLUDE_SUITE(structure_manager),
INCLUDE_SUITE(WORLD_STRUCTURES_IMPLEMENTED),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(WORLD_STRUCTURES, END_TESTS);

