#include <serialization/MAIN_TEST_SUITE_SERIALIZATION.h>

INCLUDE_SUB_SUITES(SERIALIZATION, 4,
INCLUDE_SUITE(serialization_header),
INCLUDE_SUITE(serialized_field),
INCLUDE_SUITE(hashing),NULL);

DEFINE_SUITE_WITH__SUB_SUITES(SERIALIZATION, END_TESTS);

