#ifndef SDL_UI_WINDOW__GAME__TRADE_H
#define SDL_UI_WINDOW__GAME__TRADE_H

#include <defines.h>
// THIS CODE IS AUTO GENERATED. Go to ./sdl/assets/ui/xml/ instead of modifying this file.

UI_Element *SDL_allocate_ui_for__sdl_ui_window__game__trade(Game *p_game, PLATFORM_Graphics_Window *p_PLATFORM_gfx_window, UI_Manager *p_ui_manager);
#define SDL_UI_WINDOW__GAME__TRADE_P_FILTER_BUTTON__USABLES_3 3
#define SDL_UI_WINDOW__GAME__TRADE_P_FILTER_BUTTON__WEARABLES_4 4
#define SDL_UI_WINDOW__GAME__TRADE_P_FILTER_BUTTON__CONSUMABLES_5 5
#define SDL_UI_WINDOW__GAME__TRADE_P_SLIDER_LEFT_6 6
#define SDL_UI_WINDOW__GAME__TRADE_P_SLIDER_RIGHT_7 7
#define SDL_UI_WINDOW__GAME__TRADE_P_INVENTORY_COLUMN__LEFT_8 8
#define SDL_UI_WINDOW__GAME__TRADE_P_INVENTORY_COLUMN__RIGHT_62 62
#define SDL_UI_WINDOW__GAME__TRADE_P_BG_LEFT_116 116
#define SDL_UI_WINDOW__GAME__TRADE_P_BG_RIGHT_117 117
#endif
