#include <entity/implemented/zombie/ai/MAIN_TEST_SUITE_ENTITY_IMPLEMENTED_ZOMBIE_AI.h>

INCLUDE_SUB_SUITES(ENTITY_IMPLEMENTED_ZOMBIE_AI, 1,NULL);

DEFINE_SUITE_WITH__SUB_SUITES(ENTITY_IMPLEMENTED_ZOMBIE_AI, END_TESTS);

